s3:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - "./.S3:/export"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    command: server /export
    container_name: s3-cont

postgres:
    image: postgres:latest
    ports:
        - "5432:5432" # host:container
    volumes:
       - ./.DB:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DBNAME=postgres    
        - POSTGRES_PASSWORD=mypass
        - POSTGRES_PORT=5432
    container_name: postgres-cont

redis:
    image: redis:alpine
    ports: 
        - "6379"
    container_name: redis-cont

go:
    build: .
    links:
        - postgres:db 
        - s3:s3
        - redis:redis
        # [other container]:[alias in this container]
        # this will create environment variables in the go container
        # with ip and port info for the postgres container
        # also creates entries in /etc/hosts with ip info
    ports:
        - "8080:8080" # host:container
    volumes:
       - ./go-app:/go/src/app
    environment:
        - S3_ENDPOINT=s3:9000
        - S3_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
        - S3_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    container_name: go-cont
    

